"""empty message

Revision ID: 4aff2a6d126f
Revises: e4c67105aed1
Create Date: 2021-04-29 22:09:00.141322

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4aff2a6d126f'
down_revision = 'e4c67105aed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    op.alter_column('users', 'country',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'href',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'uri',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uri',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'refresh_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'href',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'country',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('scopes', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admins_pkey'),
    sa.UniqueConstraint('email', name='admins_email_key')
    )
    # ### end Alembic commands ###
