"""empty message

Revision ID: eca6746e004b
Revises:
Create Date: 2021-04-30 17:26:50.533979

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'eca6746e004b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('href', sa.Text(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('time_signature', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('href', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.Text(), nullable=True),
    sa.Column('genre', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['artist'], ['artists.id'], name='fk_genres_artists_id_artist'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playedtracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Text(), nullable=True),
    sa.Column('track', sa.Text(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track'], ['tracks.id'], name='fk_playedtracks_tracks_id_track'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_playedtracks_users_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trackartists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.Text(), nullable=True),
    sa.Column('track', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['artist'], ['artists.id'], name='fk_trackartists_artists_id_artist'),
    sa.ForeignKeyConstraint(['track'], ['tracks.id'], name='fk_trackartists_tracks_id_track'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usertokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_usertokens_users_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usertokens')
    op.drop_table('trackartists')
    op.drop_table('playedtracks')
    op.drop_table('genres')
    op.drop_table('users')
    op.drop_table('tracks')
    op.drop_table('artists')
    # ### end Alembic commands ###
